In [33]:
import pandas as pd
import numpy as np
from numpy.linalg import inv

Q1. Pandas version

What version of Pandas did you install?

You can get the version information using the __version__ field:

In [3]:
pd.__version__

'2.3.2'

Q2. Records count

How many records are in the dataset?

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


In [6]:
df.shape

(9704, 11)

Q3. Fuel types

How many fuel types are presented in the dataset?

In [7]:
df.fuel_type.value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

In [9]:
df.fuel_type.nunique()

2

Question 4. Missing values

How many columns in the dataset have missing values?

In [10]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [11]:
df.isnull().sum().sum()

np.int64(2622)

In [12]:
(df.isnull().sum() > 0).sum()

np.int64(4)

Q5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

In [13]:
df.fuel_efficiency_mpg.max()

np.float64(25.96722204888372)

In [14]:
df.origin.value_counts()

origin
Europe    3254
Asia      3247
USA       3203
Name: count, dtype: int64

In [20]:
round(df.loc[df['origin'] == 'Asia', 'fuel_efficiency_mpg'].max(), 2)

np.float64(23.76)

Q6. Median value of horsepower

1. Find the median value of the horsepower column in the dataset.
2. Next, calculate the most frequent value of the same horsepower column.
3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
4. Now, calculate the median value of horsepower once again.
Has it changed?

Yes, it increased
Yes, it decreased
No

In [21]:
df.horsepower.median()

np.float64(149.0)

In [22]:
df.horsepower.mode()

0    152.0
Name: horsepower, dtype: float64

In [30]:
df.horsepower = df.horsepower.fillna(df.horsepower.mode()[0])

In [31]:
df.horsepower.isnull().sum()

np.int64(0)

In [32]:
df.horsepower.median()

np.float64(152.0)

Answer: Yes, the median increased after we filled in the missing values ​​in the horsepower column with the most frequent value.

Q7. Sum of weights

1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the sum of all the elements of the result?
Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [34]:
cars_asia = df[df['origin'] == 'Asia']
cars_asia.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [37]:
cars_asia[['vehicle_weight', 'model_year']].head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [36]:
X = cars_asia[['vehicle_weight', 'model_year']].head(7).values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [44]:
X.T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [38]:
XTX = X.T @ X
XTX 

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [39]:
XTX_inv = inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [40]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [42]:
w = XTX_inv @ X.T @ y
w

array([0.01386421, 0.5049067 ])

In [ ]:
np.sum(w)

np.float64(0.5187709081074016)